import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { AiMetricsLine } from "./ai-metrics-line";

describe("AiMetricsLine", () => {
  it("renders the persisted extraction stats shown on teacher and admin material lists", () => {
    const html = renderToStaticMarkup(
      <AiMetricsLine
        metrics={{
          model: "openai/gpt-5.5",
          ttftMs: 43_787,
          totalMs: 89_252,
          tokens: 2_776,
        }}
      />,
    );

    expect(html).toContain(
      "Extracted by openai/gpt-5.5 · TTFT 43.787s · gen 45.465s · total 89.252s · 2776 tokens · 61.1 tok/s",
    );
    expect(html).toContain("Dev site only");
  });

  it("renders nothing when no metrics have been persisted", () => {
    expect(renderToStaticMarkup(<AiMetricsLine metrics={{}} />)).toBe("");
  });

  it("supports generated components with an explicit aggregate generation window", () => {
    const html = renderToStaticMarkup(
      <AiMetricsLine
        prefix="Generated by "
        metrics={{
          model: "openai/gpt-5.5",
          ttftMs: 200,
          generationMs: 500,
          totalMs: 900,
          tokens: 50,
        }}
      />,
    );

    expect(html).toContain(
      "Generated by openai/gpt-5.5 · TTFT 200ms · gen 500ms · total 900ms · 50 tokens · 100.0 tok/s",
    );
  });

  it("omits AI function diagnostics from the production site", () => {
    const previousAppEnv = process.env.NEXT_PUBLIC_APP_ENV;
    process.env.NEXT_PUBLIC_APP_ENV = "prod";

    try {
      expect(
        renderToStaticMarkup(
          <AiMetricsLine metrics={{ model: "openai/gpt-5.5", tokens: 50 }} />,
        ),
      ).toBe("");
    } finally {
      if (previousAppEnv === undefined) {
        delete process.env.NEXT_PUBLIC_APP_ENV;
      } else {
        process.env.NEXT_PUBLIC_APP_ENV = previousAppEnv;
      }
    }
  });
});
