#!/usr/bin/env bash
# ============================================================================
# 04 — Compose the application .env and install it at $APP_DIR/.env on the box.
#
# WHERE: your laptop, after 01/02/03.
# TIME:  seconds.
#
#   ./scripts/04-app-env.sh
#
# Both Compose projects read this one file. Values come from config.env and
# from scripts/.state.env (written by 03), so nothing is retyped by hand and
# nothing that belongs to prod can drift away from what AWS actually created.
#
# Secrets left empty in config.env are generated here, then written back to
# config.env so a re-run produces an identical file. Rotating one is therefore
# a deliberate act: blank it in config.env and re-run.
# ============================================================================

# shellcheck source=scripts/lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
load_config
need_cmd ssh scp openssl
require_box
refresh_public_ip
require_vars APP_DIR PROD_HOST DEV_HOST AWS_REGION S3_BUCKET \
             LEARNING_MATERIAL_MAX_BYTES

require_vars CLOUDFRONT_DOMAIN CLOUDFRONT_KEY_PAIR_ID CLOUDFRONT_PRIVATE_KEY_B64 \
             APP_AWS_ACCESS_KEY_ID APP_AWS_SECRET_ACCESS_KEY

# persist_secret VAR — fill from config.env, else generate and write back.
persist_secret() {
  local var="$1" generator="$2"
  # `var` must be assigned before indirect expansion. Putting all three in one
  # `local` declaration expands ${!var} against the caller's (unset) `var` and
  # silently rotates every secret on every run.
  local value="${!var:-}"
  if [[ -z "$value" ]]; then
    value=$(eval "$generator")
    # Replace the empty assignment in place so the next run reuses it.
    if grep -q "^${var}=" "$CONFIG_FILE"; then
      sed -i.bak "s|^${var}=.*|${var}=\"${value}\"|" "$CONFIG_FILE" && rm -f "${CONFIG_FILE}.bak"
    else
      printf '%s="%s"\n' "$var" "$value" >> "$CONFIG_FILE"
    fi
    ok "generated ${var} (saved to config.env)"
  fi
  printf -v "$var" '%s' "$value"
}

step "Secrets"
persist_secret AUTH_SECRET                'openssl rand -base64 32'
persist_secret API_KEY_ENCRYPTION_SECRET  'openssl rand -hex 32'
persist_secret TEACHER_SIGNUP_TOKEN       'openssl rand -hex 12'
persist_secret ADMIN_SIGNUP_TOKEN         'openssl rand -hex 12'
ok "ready"

step "Composing .env"
OUT=$(mktemp); trap 'rm -f "$OUT"' EXIT
cat > "$OUT" <<EOF
# Generated by scripts/04-app-env.sh — do not hand-edit.
# Change scripts/config.env and re-run, or the next run silently reverts you.
# Read by both docker-compose.yml (prod) and docker-compose.dev.yml (dev).

# ---- Database -------------------------------------------------------------
# Paths are relative to /app/prisma/data inside the container, which is the
# bind mount ~/app/data/db/<env>. Compose maps the right one onto DATABASE_URL
# per environment.
PROD_DATABASE_URL="file:./data/prod.db"
DEV_DATABASE_URL="file:./data/dev.db"
DB_PROVIDER="sqlite"

# ---- Identity -------------------------------------------------------------
# The worker has no incoming request to infer a host from, so notification
# emails need this to link students straight to a message.
PROD_APP_URL="https://${PROD_HOST}"
DEV_APP_URL="https://${DEV_HOST}"
AUTH_SECRET="${AUTH_SECRET}"

# ---- Signup restriction ---------------------------------------------------
TEACHER_SIGNUP_TOKEN="${TEACHER_SIGNUP_TOKEN}"
ADMIN_SIGNUP_TOKEN="${ADMIN_SIGNUP_TOKEN}"

# ---- AI provider key encryption -------------------------------------------
# Changing this without moving the old value into API_KEY_ENCRYPTION_SECRET_OLD
# makes every stored provider key undecryptable. See SECURITY.md.
API_KEY_ENCRYPTION_SECRET="${API_KEY_ENCRYPTION_SECRET}"
API_KEY_ENCRYPTION_SECRET_OLD="${API_KEY_ENCRYPTION_SECRET_OLD:-}"

# ---- AWS ------------------------------------------------------------------
# Static keys, passed explicitly. getAwsCredentials() does not fall back to an
# instance role, and the instance has IMDS hop limit 1 so a container could not
# reach one anyway — a missing value fails loudly at startup instead of
# silently picking up whatever identity the host happens to carry.
AWS_ACCESS_KEY_ID="${APP_AWS_ACCESS_KEY_ID}"
AWS_SECRET_ACCESS_KEY="${APP_AWS_SECRET_ACCESS_KEY}"
AWS_REGION="${AWS_REGION}"
AWS_S3_BUCKET="${S3_BUCKET}"
LEARNING_MATERIAL_MAX_BYTES="${LEARNING_MATERIAL_MAX_BYTES}"

# ---- CloudFront -----------------------------------------------------------
# Reads are signed CloudFront URLs from the private OAC-only bucket; uploads
# still go straight to S3 as presigned PUTs. Clearing all three reverts
# delivery to presigned S3 with no code change and no image rebuild — that is
# the rollback switch.
CLOUDFRONT_DOMAIN="${CLOUDFRONT_DOMAIN}"
CLOUDFRONT_KEY_PAIR_ID="${CLOUDFRONT_KEY_PAIR_ID}"
CLOUDFRONT_PRIVATE_KEY="${CLOUDFRONT_PRIVATE_KEY_B64}"

# ---- Retention ------------------------------------------------------------
SYSTEM_LOG_RETENTION_DAYS="90"
EOF
ok "$(wc -l < "$OUT" | tr -d ' ') lines"

step "Installing on ${PUBLIC_IP}"
box_ssh "mkdir -p '${APP_DIR}'"
# Copy to a staging path first so a dropped connection cannot leave the
# containers reading a truncated .env on their next restart.
box_scp "$OUT" "$(box_at):${APP_DIR}/.env.staged"
box_ssh "chmod 600 '${APP_DIR}/.env.staged' && mv '${APP_DIR}/.env.staged' '${APP_DIR}/.env'"
ok "${APP_DIR}/.env installed, mode 600"

cat <<EOF

${c_green}Application environment installed.${c_reset}

The signup tokens remain in scripts/config.env (mode 600). Retrieve and share
them only through your normal secrets channel; this script does not print them.

Next: ./05-cloudflare-dns.sh
EOF
