#!/usr/bin/env bash
# ============================================================================
# 06 — Build and start Caddy, the only thing listening on the public interface.
#
# WHERE: your laptop, from a checkout of this repo.
# TIME:  ~3 minutes the first time (it compiles Caddy with the Cloudflare DNS
#        plugin), seconds afterwards.
#
#   ./scripts/06-caddy-up.sh
#
# Copies docker/Caddyfile, docker/caddy.Dockerfile and
# docker/docker-compose.caddy.yml to $CADDY_DIR on the box, generates the .env
# they read, and brings the stack up. Re-run it after editing any of those
# three files — that is the supported way to change the edge config, rather
# than editing files on the box where the next run would overwrite them.
# ============================================================================

# shellcheck source=scripts/lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
load_config
need_cmd ssh scp curl
require_box
refresh_public_ip
require_vars CADDY_DIR PROD_HOST DEV_HOST CF_API_TOKEN ACME_EMAIL

REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
for f in Caddyfile caddy.Dockerfile docker-compose.caddy.yml; do
  [[ -f "${REPO_ROOT}/docker/${f}" ]] || die "missing ${REPO_ROOT}/docker/${f} — run this from a checkout of the repo"
done

# ---------------------------------------------------------------------------
step "Collecting Cloudflare edge ranges"
# ---------------------------------------------------------------------------
# The same list that went into the security-group HTTPS rules in 01. Caddy
# gets it as a space-separated string, used for two things: deciding which
# upstream hops it may believe about client addresses, and refusing anything
# that did not arrive through Cloudflare.
CF_RANGES="$( { cf_edge_ranges_v4; cf_edge_ranges_v6; } | tr '\n' ' ' | sed 's/ $//')"
RANGE_COUNT=$(wc -w <<<"$CF_RANGES" | tr -d ' ')
[[ "$RANGE_COUNT" -ge 10 ]] || die "only ${RANGE_COUNT} ranges fetched — refusing to write a config that would lock out Cloudflare"
ok "${RANGE_COUNT} ranges"

step "Staging config on the box"
box_ssh "mkdir -p '${CADDY_DIR}/logs'"
box_scp "${REPO_ROOT}/docker/Caddyfile" \
        "${REPO_ROOT}/docker/caddy.Dockerfile" \
        "${REPO_ROOT}/docker/docker-compose.caddy.yml" \
        "$(box_at):${CADDY_DIR}/"

ENVF=$(mktemp); trap 'rm -f "$ENVF"' EXIT
cat > "$ENVF" <<EOF
# Generated by scripts/06-caddy-up.sh — do not hand-edit.
# Substituted into the Caddyfile at parse time, so a change here needs a
# container recreate (this script does that), not a config reload.
PROD_HOST=${PROD_HOST}
DEV_HOST=${DEV_HOST}
ACME_EMAIL=${ACME_EMAIL}
CF_API_TOKEN=${CF_API_TOKEN}
CF_TRUSTED_RANGES=${CF_RANGES}
EOF
box_scp "$ENVF" "$(box_at):${CADDY_DIR}/.env"
box_ssh "chmod 600 '${CADDY_DIR}/.env'"
ok "staged"

# ---------------------------------------------------------------------------
step "Validating the Caddyfile before it goes live"
# ---------------------------------------------------------------------------
# A syntax error found here costs a rebuild; found after `up -d` it costs an
# outage, because the running container exits and takes both sites with it.
box_ssh "cd '${CADDY_DIR}' && docker compose -f docker-compose.caddy.yml build --quiet" || die "image build failed"
if box_ssh "cd '${CADDY_DIR}' && docker run --rm --env-file '${CADDY_DIR}/.env' \
      -v '${CADDY_DIR}/Caddyfile:/etc/caddy/Caddyfile:ro' \
      talent-caddy:local caddy validate --config /etc/caddy/Caddyfile >/dev/null 2>&1"; then
  ok "config valid"
else
  die "caddy validate failed — fix docker/Caddyfile and re-run"
fi

step "Starting"
box_ssh "cd '${CADDY_DIR}' && docker compose -f docker-compose.caddy.yml up -d --wait --wait-timeout 120 --force-recreate"
ok "up"

# ---------------------------------------------------------------------------
step "Waiting for the first certificate"
# ---------------------------------------------------------------------------
# DNS-01 needs a TXT record to propagate before Let's Encrypt will validate,
# which usually takes 30-60s per name on a cold start.
for i in $(seq 1 60); do
  if box_ssh "docker exec talent-caddy sh -c 'find /data/caddy/certificates -type f -name \"${PROD_HOST}.crt\" | grep -q . && find /data/caddy/certificates -type f -name \"${DEV_HOST}.crt\" | grep -q .'" ; then
    ok "certificates issued for both hosts"
    break
  fi
  if [[ $i -eq 60 ]]; then
    box_ssh "docker logs --tail 50 talent-caddy 2>&1" || true
    die "both certificates were not present after 5 minutes"
  fi
  sleep 5
done

box_ssh "docker logs --tail 15 talent-caddy 2>&1" || true

cat <<EOF

${c_green}Edge is up.${c_reset}

  https://${PROD_HOST}  -> talent-web:3000
  https://${DEV_HOST}   -> talent-web-dev:3000

Nothing responds yet — the app containers do not exist until the first deploy.
Push to \`main\` (prod) or \`dev\` (dev), or run the deploy workflow by hand.

Useful:
  ssh -i ${EC2_KEY_FILE} $(box_at) 'docker logs -f talent-caddy'
  ssh -i ${EC2_KEY_FILE} $(box_at) 'tail -f ${CADDY_DIR}/logs/prod.access.log'

Next: ./09-verify.sh once a deploy has run.
EOF
